### PR TITLE
Add tier 2 mirror (cyber.123780.xyz)

### PR DESCRIPTION
**Pull request by darksunlight**
This PR adds my CyberOS mirror. Syncs daily from a tier 1 source at around 11 am EDT (UTC-4).

### CODE REVIEW

**Comment by omaemae** [comment]
you didn't update the PKGBUILD! (make sure your md5sums are computed with Unix file endings, we had it mess up once)

**Comment by darksunlight** [comment]
oops! Fixing

**Comment by omaemae** [comment]
alright, i did it for you

**Comment by omaemae** [comment]
the mirror works fine, merging

if the mirror goes down or goes out of sync, we'll notify you in a GitHub issue

**Pull request merged**
